DjangoAirERP/customer/urls.py
from django.urls import path
from .views import (Index, FlightView, FlightReservationView, CustomerUpdate, TicketListView,
                    TicketDetailView, TicketRegisterView, TicketSearchView)

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('flights/search', FlightView.as_view(), name='flights_search'),
    path('flights/<int:pk>/reservation', FlightReservationView.as_view(), name='flights_reservation'),
    path('cabinet/<int:pk>/update', CustomerUpdate.as_view(), name='customer_update'),
    path('cabinet/<int:pk>/tickets', TicketListView.as_view(), name='customer_tickets'),
    path('cabinet/<int:id>/tickets/<int:pk>', TicketDetailView.as_view(), name='ticket_detail'),
    path('cabinet/<int:id>/tickets/search', TicketSearchView.as_view(), name='ticket_search'),
    path('cabinet/<int:id>/tickets/<int:pk>/register', TicketRegisterView.as_view(), name='ticket_reg'),
]

DjangoAirERP/management/models.py
from django.core.validators import MinValueValidator, MinLengthValidator, RegexValidator
from django.db import models
from management.validators import min_date_validator
from user_model.models import User


class City(models.Model):
    name = models.CharField(max_length=50)
    country = models.CharField(max_length=2)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name} {self.country}'


class Airplane(models.Model):
    location = models.ForeignKey(City, on_delete=models.CASCADE, related_name='cities')
    model = models.CharField(max_length=200)
    name = models.CharField(max_length=200, unique=True)
    comfort_places = models.IntegerField(validators=[MinValueValidator(limit_value=1,
                                                                       message='Minimum number of places 1.')])
    economy_places = models.IntegerField(validators=[MinValueValidator(limit_value=1,
                                                                       message='Minimum number of places 1.')])
    date_registration = models.DateField(auto_now_add=True)
    busy_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Airport(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='airports')
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Option(models.Model):
    SERVICE_TYPE = {
        ('included', 'Included'),
        ('extra', 'Extra')
    }
    option = models.CharField(max_length=100)
    price = models.FloatField(validators=[MinValueValidator(limit_value=1, message='Minimum number of seats 1.')])
    weight = models.IntegerField(null=True)
    service_type = models.CharField(max_length=8, choices=SERVICE_TYPE, null=True)

    def __str__(self):
        if self.weight:
            return f'{self.option} {self.weight}kg - {self.service_type}'
        return f'{self.option} - {self.service_type}'


class Flight(models.Model):
    airplane = models.ForeignKey(Airplane, on_delete=models.CASCADE, related_name='flights')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='from_city')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='to_city')
    from_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='from_airport')
    to_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='to_airport')
    departure_date = models.DateTimeField(validators=[min_date_validator])
    date_arrival = models.DateTimeField(validators=[min_date_validator])
    flight_time = models.CharField(max_length=20)
    option = models.ManyToManyField(Option)
    date_registration = models.DateTimeField(auto_now_add=True)
    price = models.FloatField(validators=[MinValueValidator(limit_value=1, message='Minimum number of seats 1.')])

    class Meta:
        ordering = ('-date_registration',)

    def __str__(self):
        return f'{self.from_city} --> {self.to_city}'


class Discount(models.Model):
    name = models.CharField(unique=True, max_length=20)
    percents = models.CharField(max_length=4)
    valid_until = models.DateField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.percents


class Ticket(models.Model):
    PASSENGER = (
        ('adult', 'Adult'),
        ('child ', 'Child'),
        ('infant', 'Infant')
    )

    GENDER = (
        ('male', 'Male'),
        ('female', 'Female')
    )

    PLACE_TYPE = (
        ('economy', 'Economy'),
        ('comfort', 'Comfort')
    )

    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='purchases')
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, related_name='tickets')
    reservation = models.BooleanField(default=False)
    date_reservation = models.DateTimeField(null=True)
    first_name = models.CharField(null=True, max_length=30,
                                  validators=[MinLengthValidator(limit_value=1, message='Minimum length 1 character.')])
    last_name = models.CharField(null=True, max_length=30,
                                 validators=[MinLengthValidator(limit_value=1, message='Minimum length 1 character.')])
    years_old = models.CharField(null=True, max_length=8, choices=PASSENGER)
    place = models.IntegerField(null=True,
                                validators=[MinValueValidator(limit_value=1, message='Minimum number of seats 1.')])
    price = models.FloatField(validators=[MinValueValidator(limit_value=1, message='Minimum number of seats 1.')])
    price_with_options = models.FloatField(null=True, validators=[
        MinValueValidator(limit_value=1, message='Minimum number of seats 1.')])
    date_birthday = models.DateField(null=True)
    gender = models.CharField(max_length=6, choices=GENDER, null=True, default=None)
    document_no = models.CharField(max_length=8, null=True, validators=[RegexValidator(
        regex=r"[A-Za-z]{2}[0-9]{6}",
        message='The form is filled in with the first two letters and six digits.')])
    payment_status = models.BooleanField(default=False)
    check_in = models.BooleanField(default=False)
    self_check_in = models.BooleanField(default=False)
    place_type = models.CharField(max_length=7, choices=PLACE_TYPE)
    discount = models.ForeignKey(Discount, blank=True, null=True, on_delete=models.CASCADE, related_name='discounts')
    included_options = models.ManyToManyField(Option, blank=True, related_name='included_options')
    extra_options = models.ManyToManyField(Option, blank=True, related_name='extra_options')
    luggage_weight = models.IntegerField(null=True)
    boarding = models.BooleanField(default=False)
    boarding_time = models.DateTimeField(null=True)

    @property
    def get_price_ticket_child(self):
        return round(self.price * 0.5, 2)

    @property
    def get_price_ticket_infant(self):
        return round(self.price * 0.1, 2)

    @property
    def get_place(self):
        if self.place:
            return self.place
        return 'Not registered'

DjangoAirERP/customer/views.py
from django.forms import formset_factory
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import UpdateView, ListView, DetailView, View
from customer.forms import TicketReservationForm, CustomerForm, TicketRegisterForm, SearchByCodeForm
from customer.utils import send_tickets_by_mail
from management.models import Flight, Ticket, Option, Discount
from management.utils import get_free_place
from user_model.models import User
from datetime import datetime


class Index(View):
    def get(self, request):
        """Home Page."""
        return render(request, 'index.html', {'min_date': str(datetime.today().date())})


class FlightView(View):

    def get(self, request):
        """Search for flights and available tickets."""
        try:
            args = request.GET
            flights = Flight.objects.filter(departure_date__icontains=args['date'],
                                            to_city__name__startswith=args['to_city'],
                                            from_city__name__startswith=args['from_city']
                                            ).select_related(
                'from_city').select_related('to_city').select_related('from_airport').select_related('to_airport')

            filtered_flights = self.get_filtered_flights(flights, args)
            return render(request, 'flights/flight.html', {'min_date': str(datetime.today().date()),
                                                           'initial': args,
                                                           'flights': filtered_flights})
        except Exception:
            return render(request, 'flights/flight.html', {'error': 'Not all fields are filled in for the search.'})

    def get_filtered_flights(self, flights, args):
        """Filter for flights by number of available tickets and price calculation."""
        adults, children, infants = int(args['adults']), int(args['children']), int(args['infants'])

        filtered_flights = []
        for flight in flights:
            tickets = Ticket.objects.filter(flight=flight, reservation=False, place_type=args['class'])
            if len(tickets) >= sum([adults, children, infants]):
                ticket = tickets.first()
                price = sum([ticket.price * adults,
                             ticket.get_price_ticket_child * children,
                             ticket.get_price_ticket_infant * infants])
                included_options = [option['option'] for option in flight.option.filter(service_type='included'
                                                                                        ).values('option')]
                filtered_flights.append([flight, price, len(tickets), included_options])
        return filtered_flights


class FlightReservationView(View):
    def get(self, request, pk):
        """Sending ticket forms to fill out."""
        flight = Flight.objects.filter(pk=pk).select_related('from_city').select_related(
            'to_city').select_related('from_airport').select_related('to_airport').first()
        options = flight.option.all()
        adults, children, infants = self.get_formsets(request.GET)
        ticket = flight.tickets.filter(place_type=request.GET['class']).first()
        price = sum([ticket.price * len(adults),
                     ticket.get_price_ticket_child * len(children),
                     ticket.get_price_ticket_infant * len(infants)])

        return render(request, 'flights/flight_reservation.html', {
            'flight': flight,
            'adults': adults,
            'children': children,
            'infants': infants,
            'price': price,
            'class': request.GET['class'],
            'extra_options': options.filter(service_type='extra'),
            'options': [option['option'] for option in options.filter(service_type='included').values('option')]})

    def post(self, request, pk):
        """If the forms are filled out correctly, they are booked and the tickets are mailed."""
        formset = formset_factory(TicketReservationForm)
        adult, children, infants = (formset(request.POST, prefix='adult'),
                                    formset(request.POST, prefix='children'),
                                    formset(request.POST, prefix='infants'))
        if adult.is_valid() and children.is_valid() and infants.is_valid():
            tickets_id = []
            for forms in [adult, children, infants]:
                tickets_id += self.book_tickets(pk, request.POST['class'], request.user, forms)
            send_tickets_by_mail(tickets_id, request.user)
            return JsonResponse(data={'url': reverse('customer_tickets', kwargs={'pk': request.user.pk})}, status=200)

        errors = self.get_errors(adult, children, infants)
        return JsonResponse(data={'error': errors}, status=401)

    def book_tickets(self, flight_id, place_type, owner, forms):
        """Fills in all ticket data and stores it in the database."""
        tickets = Ticket.objects.filter(flight_id=flight_id, reservation=False, place_type=place_type)[:len(forms)]
        tickets_id = []
        for ticket, form in zip(tickets, forms):
            ticket.owner = owner
            ticket.reservation = True
            ticket.first_name = form.cleaned_data['first_name']
            ticket.last_name = form.cleaned_data['last_name']
            ticket.years_old = forms.prefix
            ticket.date_birthday = form.cleaned_data['date_birthday']
            ticket.gender = form.cleaned_data['gender']
            ticket.document_no = form.cleaned_data['document_no']
            ticket.place_type = place_type
            ticket.date_reservation = datetime.today()
            price = self.get_price_ticket(ticket, forms.prefix)
            ticket.price = price

            if f'{form.prefix}-extra_options' in forms.data:
                extra_options_id = forms.data.getlist(f'{form.prefix}-extra_options')
                price = self.add_extra_options(ticket, price, extra_options_id)
            ticket.price_with_options = price
            ticket.save()
            tickets_id.append(ticket.id)

        return tickets_id

    def get_price_ticket(self, ticket, type_ticket):
        """Returns the price of the ticket by age."""
        if type_ticket == 'adult':
            return ticket.price
        elif type_ticket == 'children':
            return ticket.get_price_ticket_child
        else:
            return ticket.get_price_ticket_infant

    def add_extra_options(self, ticket, price, extra_options_id):
        """Adds all additional options selected to the ticket."""
        options = Option.objects.filter(id__in=extra_options_id)
        for option in options:
            price += option.price
            ticket.extra_options.add(option)
        return price

    def get_errors(self, *formsets):
        """Returns all errors in the ticket forms."""
        return ''.join(set([f'{error.as_text()}\n'
                            for form in formsets if len(form.errors) > 0
                            for errors in form.errors
                            for error in errors.values()]))

    def get_formsets(self, args):
        """Returns sets of forms with age prefixes for the tickets."""
        adult_formset = formset_factory(TicketReservationForm, extra=int(args['adults']))
        children_formset = formset_factory(TicketReservationForm, extra=int(args['children']))
        infants_formset = formset_factory(TicketReservationForm, extra=int(args['infants']))
        return adult_formset(prefix='adult'), children_formset(prefix='children'), infants_formset(prefix='infants')


class CustomerUpdate(UpdateView):
    """Changing account information."""
    model = User
    form_class = CustomerForm
    template_name = 'personal_cabinet/personal_cabinet.html'
    context_object_name = 'customer_update'

    def get_success_url(self):
        return reverse('customer_update', kwargs={'pk': self.kwargs['pk']})


class TicketListView(ListView):
    """List of tickets purchased."""
    model = Ticket
    template_name = 'personal_cabinet/personal_cabinet.html'
    paginate_by = 10

    def get_queryset(self):
        return Ticket.objects.filter(owner=self.kwargs['pk']).select_related(
            'flight__from_city').select_related('flight__to_city').order_by('-date_reservation')


class TicketDetailView(DetailView):
    """Ticket information."""
    model = Ticket
    template_name = 'personal_cabinet/personal_cabinet.html'

    def get_queryset(self):
        return Ticket.objects.filter(pk=self.kwargs['pk']).select_related('flight__from_city').select_related(
            'flight__to_city').select_related('flight__from_airport').select_related('flight__to_airport')


class TicketSearchView(View):
    def get(self, request, **kwargs):
        """Search for a ticket by code."""
        if 'code' in request.GET:
            ticket = Ticket.objects.filter(id=request.GET['code'],
                                           owner=request.user,
                                           self_check_in=False,
                                           check_in=False).first()
            if ticket:
                return redirect('ticket_reg', request.user.id, ticket.id)
            return render(request, 'personal_cabinet/personal_cabinet.html',
                          {'form_search': SearchByCodeForm,
                           'error': 'Unregistered ticket with this code is not found.'})
        return render(request, 'personal_cabinet/personal_cabinet.html', {'form_search': SearchByCodeForm})


class TicketRegisterView(UpdateView):
    """Ticket registration in the personal cabinet.
    (Add a place add a discount)"""
    model = Ticket
    template_name = 'personal_cabinet/personal_cabinet.html'
    form_class = TicketRegisterForm
    context_object_name = 'ticket_reg'

    def form_valid(self, form):

DjangoAirERP/customer/templates/personal_cabinet/cabinet_button.html
<div class="row card-button">
    <div class="div-bi">
        <i class="bi bi-person-fill"></i>
    </div>
    <div class="desc-button">
        <a href="{% url "customer_update" user.id %}" class="btn options">
            Account detail
        </a>
    </div>
</div>

<div class="row card-button">
    <div class="div-bi">
        <i class="bi bi-ticket-detailed"></i>
    </div>
    <div class="desc-button">
        <a href="{% url "customer_tickets" user.id %}" class="btn options">
            My tickets
        </a>
    </div>
</div>

<div class="row card-button">
    <div class="div-bi">
        <i class="bi bi-ticket-detailed"></i>
    </div>
    <div class="desc-button">
        <a href="{% url "ticket_search" user.id %}" class="btn options">
            Ticket registration
        </a>
    </div>
</div>

DjangoAirERP/customer/templates/personal_cabinet/customer_update.html
{% if customer_update %}
    <div class="div-descr-card">
        <h5><b>Your account information</b></h5>
        <form action="{% url "customer_update" user.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <p><input class="btn btn-warning customer-btn" type="submit" value="Change"/></p>
        </form>
    </div>
{% endif %}

DjangoAirERP/customer/templates/personal_cabinet/personal_cabinet.html
{% extends "base.html" %}
{% load static %}

{% block title %}My account{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/customer/personal_cabinet.css' %}">
{% endblock %}

{% block content %}
    <div class="container my-contain" align="center">
        <div class="card main-card">
            <div class="row">
                <div class="customer-buttons">
                    {% include "personal_cabinet/cabinet_button.html" %}
                </div>
                {% if user == request.user %}
                    {% include "personal_cabinet/customer_update.html" %}
                    {% include "personal_cabinet/ticket_purchases.html" %}
                    {% include "personal_cabinet/ticket_detail.html" %}
                    {% include "personal_cabinet/ticket_reg.html" %}
                {% endif %}
                <div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

DjangoAirERP/customer/templates/personal_cabinet/ticket_detail.html
{% if ticket %}
    <div class="div-descr-card">
        <div class="row"></div>
        <h5>Ticket <small><b>code: {{ object.id }}</b></small>{% include "personal_cabinet/ticket_info.html" %}</h5>
        <div class="row">
            <div>
                <p>
                    <b>{{ object.flight.from_city.name }}</b>
                    <small>{{ object.flight.departure_date }}</small>
                    <i class="bi bi-arrow-right"></i>
                    <b>{{ object.flight.to_city.name }}</b>
                    <small>{{ object.flight.date_arrival }}</small>
                </p>
                <p>
                    Airport: <b>{{ object.flight.from_airport }}</b>
                    <i class="bi bi-arrow-right"></i>
                    Airport: <b>{{ object.flight.to_airport }}</b>
                </p>
                <p class="date-pub">
                    <small>Date of reservation: {{ object.date_reservation }}</small>
                </p>
            </div>
        </div>
    </div>
{% endif %}

DjangoAirERP/customer/templates/personal_cabinet/ticket_info.html
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/customer/ticket_info.css' %}">
{% endblock %}

<button type="button" class="btn form-btn btn-info" data-bs-toggle="modal" data-bs-target="#TicketInfo">
    Ticket information
</button>

<div class="modal fade" id="TicketInfo" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table table-light ticket-tabl">
                    <thead>
                        <tr class="name-field">
                            <th scope="col">Name</th>
                            <th scope="col">Surname</th>
                            <th scope="col">Years old</th>
                            <th scope="col">Birthday</th>
                            <th scope="col">Gender</th>
                            <th scope="col">Document no</th>
                            <th scope="col">Self check-in</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td scope="row">{{ ticket.first_name }}</td>
                        <td>{{ ticket.last_name }}</td>
                        <td>{{ ticket.years_old }}</td>
                        <td>{{ ticket.date_birthday }}</td>
                        <td>{{ ticket.gender }}</td>
                        <td>{{ ticket.document_no }}</td>
                        <td>{{ ticket.self_check_in }}</td>
                    </tr>
                    </tbody>
                      <thead>
                        <tr class="name-field">
                            <th scope="col">Place</th>
                            <th scope="col">Type</th>
                            <th scope="col">Extra</th>
                            <th scope="col">Included</th>
                            <th scope="col">Price ticket</th>
                            <th scope="col">Discount</th>
                            <th scope="col">Price to pay</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ ticket.get_place }}</td>
                        <td>{{ ticket.place_type }}</td>
                        <td>
                            {% for option in ticket.extra_options.all %}
                                {{ option.option }}  {{ option.weight }}kg
                            {% endfor %}
                        </td>
                        <td>
                            {% for option in ticket.included_options.all %}
                                {{ option.option }}
                            {% endfor %}
                        </td>
                        <td>{{ ticket.price }}$</td>
                        <td>{{ ticket.discount }}</td>
                        <td>{{ ticket.price_with_options }}$</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

DjangoAirERP/customer/templates/personal_cabinet/ticket_purchases.html
{% if ticket_list %}
    <div class="div-descr-card">
        <h5><b>My purchases</b></h5>
        {% for ticket in ticket_list %}
            <div class="row">
                <div class="ticket-num">
                    № {{ forloop.counter }}
                </div>
                <div class="block-active">
                    {% if ticket.landing %}
                        <i class="bi bi-earlier bi-broadcast"></i>
                    {% else %}
                        <i class="bi bi-later bi-broadcast"></i>
                    {% endif %}
                </div>

                <div class="ticket-list-block">
                    <a href="{% url "ticket_detail" request.user.id ticket.id %}" id="ticket-btn"
                       class="btn btn-outline-dark">
                        <b>{{ ticket.flight.from_city.name }}</b>
                        <small>{{ ticket.flight.departure_date|date:'j F Y' }}</small>
                        <i class="bi bi-arrow-right"></i>
                        <b>{{ ticket.flight.to_city.name }}</b>
                        <small>{{ ticket.flight.date_arrival|date:'j F Y' }}</small>
                    </a>
                </div>
            </div>
            <hr>
        {% endfor %}
        {% if page_obj.has_other_pages %}
            <br>
            {% include "pagination.html" %}
        {% endif %}
    </div>
{% endif %}

DjangoAirERP/customer/templates/personal_cabinet/ticket_reg.html
{% if form_search %}

    <div class="div-descr-card">
        <h5><b>Enter ticket code</b></h5>
        {% if error %}
            <div class="alert alert-danger" id="tickets_alert" style="" role="alert">{{ error }}</div>
        {% endif %}
        <form action="{% url "ticket_search" user.id %}" method="get">
            {% csrf_token %}
            {{ form_search }}
            <p><input class="btn btn-warning customer-btn" type="submit" value="Search"/></p>
        </form>
    </div>

{% elif ticket_reg %}

    <div class="div-descr-card">
        <h5><b>Register a ticket</b></h5>
        <form action="{% url "ticket_reg" user.id ticket_reg.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <p><input class="btn btn-warning customer-btn customer-input" type="submit" value="Register"/></p>
        </form>
        <p align="left">- The ticket will become registered to you.</p>
        <p align="left">- Your place will be indicated on the ticket.</p>
    </div>

{% endif %}